# fly.toml app configuration file generated for procuratio-fra on 2025-01-24T14:01:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'procuratio-fra'
primary_region = 'fra'

kill_timeout = 30
swap_size_mb = 256

[[vm]]
size = 'shared-cpu-1x'

[build]
image = "tailscale/tailscale:v1.78.1"

[mounts]
source = "procuratio_fra_data"
destination = "/data"
initial_size = "1gb"

[deploy]
strategy = "rolling"

[env]
TS_HOSTNAME = "procuratio-fra"
TS_STATE_DIR = "/data/tailscaled"
TS_EXTRA_ARGS = "--advertise-connector"

# Set in secrets
# TS_AUTHKEY = "tskey-auth-…"
